USE BloodOct2;

CREATE TABLE HOSPITAL_INFO(
ID INT PRIMARY KEY IDENTITY,
NAME VARCHAR(50),
TRANSFER_REQ INT,
);

CREATE TABLE BLOOD_NUM(
ID INT,
Aplus INT,
Aminus INT,
Bplus INT,
Bminus INT,
ABplus INT,
ABminus INT,
Oplus INT,
Ominus INT,
FOREIGN KEY(ID) REFERENCES HOSPITAL_INFO(ID)
);
DROP TABLE BLOOD_NUM;
INSERT INTO BLOOD_NUM VALUES(2,1,2,3,0,0,0,0,0);
INSERT INTO HOSPITAL_INFO VALUES('ZEWDITU',10);
SELECT *FROM HOSPITAL_INFO;
SELECT *FROM BLOOD_NUM
DROP TABLE HOSPITAL_INFO;