Use BloodBankSql;

CREATE TRIGGER BLOOD_COUNT_INCREMENT
ON SUCCESSFUL_DONATION
AFTER INSERT
AS
BEGIN
	DECLARE @type varchar(3);
	SELECT @type = BloodType from INSERTED;
	UPDATE BLOOD_COUNT set bloodcount += 1 where bloodtype = @type;
END

CREATE TRIGGER PHONE_EMAIL_VERIFICATION
ON DONOR_INFO
AFTER INSERT
AS
BEGIN
	DECLARE @phone varchar(30), @email varchar(50);
	SELECT @phone = Phone, @email = Email from INSERTED;
	IF EXISTS(SELECT * from DONOR_INFO where Phone = @phone or Email = @email)
		BEGIN
			-- delete sp
		END
END

-- ANOTHER TRIGGER FOR REQUESTING DONATION WITH PERMANENT ILLNESS
-- ADDING TO FAILED_HISTORY
-- SUCCESSFUL DONATION 3 MONTHS FROM LAST DONATINON
			
	

